services:

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - spring-microservices-network

  eureka-server:
    build: ./microservicios-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - spring-microservices-network

  microservices-users:
    build: ./microservices-users
    container_name: microservices-users-container
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
      - mysql-users
    networks:
      - spring-microservices-network

  microservices-cursos:
    build: ./microservicios-cursos
    container_name: microservices-cursos-container
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
      - postgres-cursos
    networks:
      - spring-microservices-network

  microservices-exams:
    build: ./microservices-exams
    container_name: microservices-exams-container
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
      - mongo-services
    networks:
      - spring-microservices-network

  microservices-payments:
    build: ./microservices-payments
    container_name: microservices-payments-container
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - eureka-server
      - mongo-payments
    networks:
      - spring-microservices-network

  microservices-gateway:
    build: ./microservices-gateway
    container_name: microservices-gateway-container
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - spring-microservices-network


  mysql-users:
    image: mysql:8
    container_name: mysql-users
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db_microservicios_examenes
    volumes:
      - mysql-users-data:/var/lib/mysql
    networks:
      - spring-microservices-network

  postgres-cursos:
    image: postgres:15
    container_name: postgres-cursos
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db_microservicios_cursos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-cursos-data:/var/lib/postgresql/data
    networks:
      - spring-microservices-network

  mongo-payments:
    image: mongo:7
    container_name: mongo-payments
    ports:
      - "27017:27017"
    volumes:
      - mongo-payments-data:/data/db
    networks:
      - spring-microservices-network

  mongo-services:
    image: mongo:7
    container_name: mongo-services
    ports:
      - "27018:27017"
    volumes:
      - mongo-services-data:/data/db
    networks:
      - spring-microservices-network

networks:
  spring-microservices-network:
    driver: bridge

volumes:
  mysql-users-data:
  postgres-cursos-data:
  mongo-payments-data:
  mongo-services-data: